In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print (tf.__version__)

1.15.0


## Defining Tensors

In [0]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
              [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

In [0]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [0]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:
sess = tf.Session()
print ("OPEN SESSION")

OPEN SESSION


In [0]:
def print_tf(x):
    print("TYPE IS\n %s" % (type(x)))
    print("VALUE IS\n %s" % (x))

## Constants

In [0]:
hello = tf.constant("Hello World!")
print(hello)
print_tf(hello)

Tensor("Const_3:0", shape=(), dtype=string)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_3:0", shape=(), dtype=string)


In [0]:
hello_out = sess.run(hello)
print_tf(hello_out)

TYPE IS
 <class 'bytes'>
VALUE IS
 b'Hello World!'


In [0]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_4:0", shape=(), dtype=float32)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_5:0", shape=(), dtype=float32)


In [0]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 1.5
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 2.5


## Operations


In [0]:
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Add:0", shape=(), dtype=float32)


In [0]:
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 4.0


In [0]:
a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 3.75


## Variables

In [0]:
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [0]:
tf.Variable?

In [0]:
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: ignored

In [0]:
sess.run(weight.initializer)

In [0]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.04743151  0.00253516]
 [-0.15510917 -0.01360293]
 [-0.17814426  0.08017371]
 [ 0.00544862  0.1924896 ]
 [-0.01959358  0.00671494]]


In [0]:
weight2 = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
weight3 = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight2)
print_tf(weight3)

TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable_1:0' shape=(5, 2) dtype=float32_ref>
TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable_2:0' shape=(5, 2) dtype=float32_ref>


In [0]:
init = tf.global_variables_initializer()
sess.run(init)

In [0]:
weight_out2 = sess.run(weight2)
weight_out3 = sess.run(weight3)
print_tf(weight_out2)
print_tf(weight_out3)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.01173182 -0.22001612]
 [-0.12494975  0.09086003]
 [-0.21507402 -0.0190808 ]
 [-0.10145617  0.04007291]
 [-0.10149921 -0.06103851]]
TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.08317298  0.09363919]
 [-0.06230816  0.02113264]
 [ 0.02592087  0.00352657]
 [ 0.01010869 -0.04505456]
 [-0.01308436 -0.09546875]]


In [0]:
s = tf.Variable(2, name='scalar') 
m = tf.Variable([[0, 1], [2, 3]], name='matrix') 
W = tf.Variable(tf.zeros([784,10]), name='big_matrix')
V = tf.Variable(tf.truncated_normal([784, 10]), name='normal_matrix')

s = tf.get_variable('scalar', initializer=tf.constant(2)) 
m = tf.get_variable('matrix', initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.zeros_initializer())
V = tf.get_variable('normal_matrix', shape=(784, 10), initializer=tf.truncated_normal_initializer())

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(V.eval())

[[ 0.03665987 -1.4132723  -0.9677544  ... -0.9335785   0.3941228
   1.2951479 ]
 [ 0.75348014 -1.2934006   0.00534437 ...  0.01588563  1.0807947
  -0.9799453 ]
 [-1.6136978  -0.39328477 -0.29909614 ...  1.1248938  -0.8716928
   1.0251876 ]
 ...
 [ 0.93366486  0.30626696  0.6448282  ... -0.40923768  0.7005336
   0.5148733 ]
 [ 0.1939294   0.08603391  0.91904956 ...  1.2070066  -0.29831472
   0.33835918]
 [-0.9623086   0.19269153 -0.36467832 ... -0.20256121 -1.4601862
   0.33683056]]


## Placeholders

In [0]:
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


In [0]:
oper = tf.matmul(x, weight)
print_tf(oper)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [0]:
#sess = tf.Session()
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.21235275  0.23158918]]


In [0]:
data = np.random.rand(2, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.30549684  0.1025347 ]
 [-0.17296925  0.18816826]]


In [0]:
sess.close()